In [3]:
import torch
import numpy as np

In [4]:
num_inputs = 2
num_examples = 1000
true_w = [2, -3.4]
true_b = 4.2
features = torch.tensor(np.random.normal(0, 1, (num_examples, num_inputs)), dtype=torch.float)
labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] + true_b
labels += torch.tensor(np.random.normal(0, 0.01, size=labels.size()), dtype=torch.float)

In [11]:
import torch.utils.data as Data
batch_size = 10
dataset = Data.TensorDataset(features, labels)

data_iter = Data.DataLoader(dataset, batch_size, shuffle=True)
i = 0
for X, y in data_iter:
    print(X, y)

tensor([[-2.7065e-01, -1.8229e+00],
        [-1.9922e-03,  1.5641e+00],
        [ 2.4006e-01, -2.2932e+00],
        [-1.7793e-01,  1.6066e+00],
        [-1.4167e+00,  1.2988e+00],
        [ 9.2796e-01, -7.9100e-01],
        [ 1.9120e-01, -2.9588e-01],
        [ 6.5809e-01, -4.4988e-01],
        [-1.6729e-02, -1.7233e+00],
        [-5.4713e-02,  5.4075e-01]]) tensor([ 9.8564, -1.1171, 12.4703, -1.6200, -3.0477,  8.7344,  5.5755,  7.0475,
        10.0237,  2.2501])
1
tensor([[ 1.3296,  0.2001],
        [-0.1864,  0.3011],
        [ 0.7707,  0.9590],
        [ 1.5109, -1.4120],
        [-0.2126,  0.2230],
        [-0.2708,  0.7688],
        [ 0.3260, -0.8337],
        [ 0.3549, -1.5400],
        [ 0.1634, -0.1785],
        [ 0.1560, -0.2551]]) tensor([ 6.1796,  2.8036,  2.4795, 12.0273,  3.0197,  1.0518,  7.6571, 10.1537,
         5.1407,  5.3827])
2
tensor([[ 0.9363,  0.4718],
        [ 0.3201,  0.1864],
        [ 0.3871,  0.3758],
        [ 0.1538,  0.5978],
        [-1.1528,  1.1530],


In [13]:
import torch.nn as nn
class LinearNet(nn.Module):
    def __init__(self, n_feature):
        super(LinearNet, self).__init__()
        self.linear = nn.Linear(n_feature, 1)

    def forward(self, x):
        y = self.linear(x)
        return y

net = LinearNet(num_inputs)
print(net)


LinearNet(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)


In [14]:
for param in net.parameters():
    print(param)


Parameter containing:
tensor([[0.0083, 0.1371]], requires_grad=True)
Parameter containing:
tensor([0.1827], requires_grad=True)
