In [1]:
import torch
import numpy as np

In [2]:
num_inputs = 2
num_examples = 1000
true_w = [2, -3.4]
true_b = 4.2
features = torch.tensor(np.random.normal(0, 1, (num_examples, num_inputs)), dtype=torch.float)
labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] + true_b
labels += torch.tensor(np.random.normal(0, 0.01, size=labels.size()), dtype=torch.float)

In [3]:
import torch.utils.data as Data
batch_size = 10
dataset = Data.TensorDataset(features, labels)

data_iter = Data.DataLoader(dataset, batch_size, shuffle=True)
i = 0
for X, y in data_iter:
    print(X, y)
    break

tensor([[ 0.8103,  1.3601],
        [ 1.4908,  0.5497],
        [ 0.5467,  1.4335],
        [-0.5393,  0.4679],
        [ 2.6425, -0.2785],
        [-0.4878,  0.1926],
        [ 0.7592,  0.5992],
        [-0.9120,  0.6589],
        [ 1.7155, -0.1554],
        [-0.9274,  1.1414]]) tensor([ 1.1888,  5.3135,  0.4316,  1.5130, 10.4365,  2.5684,  3.6871,  0.1512,
         8.1848, -1.5389])


In [18]:
# 定义模型
import torch.nn as nn
# class LinearNet(nn.Module):
#     def __init__(self, n_feature):
#         super(LinearNet, self).__init__()
#         self.linear = nn.Linear(n_feature, 1)
#
#     def forward(self, x):
#         y = self.linear(x)
#         return y
#
# net = LinearNet(num_inputs)

net = nn.Sequential(
    nn.Linear(num_inputs, 1)
    # 此处还可以传入其他层
    )

print(net)
print(net[0])

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
)
Linear(in_features=2, out_features=1, bias=True)


In [5]:
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[-0.2251, -0.2352]], requires_grad=True)
Parameter containing:
tensor([-0.0319], requires_grad=True)


In [12]:
# net[0].weight

In [19]:
# 初始化模型参数
nn.init.normal_(net[0].weight, mean=0, std=0.01)
nn.init.constant_(net[0].bias, val=0)


Parameter containing:
tensor([0.], requires_grad=True)

In [ ]:
# 定义损失函数
loss = nn.MSELoss()

In [20]:
# 定义优化算法
optimizer = torch.optim.SGD(net.parameters(), lr=0.03)
print(optimizer)


SGD (
Parameter Group 0
    dampening: 0
    lr: 0.03
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [ ]:
# 训练模型

