In [29]:
import torch

In [30]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [31]:
Q = 3*a*3 - b**2
Q


tensor([-18.,  11.], grad_fn=<SubBackward0>)

In [32]:
Q.backward(gradient=torch.tensor([1., 1.]))
print(a.grad)
print(b.grad)

tensor([9., 9.])
tensor([-12.,  -8.])
