In [1]:
import torch
import numpy as np


In [3]:
tensor = torch.rand(3, 4)
print(f"Shape of tesnor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tesnor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [4]:
tensor.mul(tensor)

tensor([[3.0489e-01, 2.0699e-03, 5.0637e-01, 4.9744e-01],
        [5.4929e-02, 9.6234e-01, 4.8351e-01, 6.0920e-01],
        [3.4847e-04, 1.4459e-01, 9.1737e-01, 5.5234e-01]])

In [5]:
tensor2 = torch.tensor([[1, 2], [3, 4]])
tensor3 = tensor2 * tensor2
print(tensor3)

tensor([[ 1,  4],
        [ 9, 16]])


In [6]:
# 索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改
tensor4 = tensor2[:,0]
tensor4 += 1

print(tensor2)
print(tensor4)


tensor([[2, 2],
        [4, 4]])
tensor([2, 4])


In [12]:
# broadcast
x = torch.arange(1, 3).view(1, 2)
y = torch.arange(1, 4).view(3, 1)

print(x+y)

tensor([[2, 3],
        [3, 4],
        [4, 5]])
